# Generated by Django 5.0.6 on 2024-08-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="liquidated_at",
            field=models.DateTimeField(null=True),
        ),
    ]
