# Generated by Django 5.0.6 on 2024-08-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0005_alter_blacklist_reserve_eth"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="bot",
            field=models.CharField(max_length=42, null=True),
        ),
        migrations.AddField(
            model_name="position",
            name="signer",
            field=models.CharField(max_length=42, null=True),
        ),
    ]
