# Generated by Django 5.0.6 on 2024-08-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0006_position_bot_position_signer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blacklist",
            name="reserve_eth",
        ),
        migrations.AddField(
            model_name="blacklist",
            name="address",
            field=models.CharField(max_length=42, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="pair",
            name="creator",
            field=models.CharField(max_length=42, null=True),
        ),
        migrations.AddIndex(
            model_name="pair",
            index=models.Index(fields=["creator"], name="pair_creator_a07107_idx"),
        ),
    ]
