# Generated by Django 5.0.6 on 2024-08-14 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0008_pair_pair_address_1079d9_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="pair",
            name="pair_address_1079d9_idx",
        ),
    ]
