# Generated by Django 5.0.6 on 2024-08-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0009_remove_pair_pair_address_1079d9_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bot",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("address", models.CharField(max_length=42, unique=True)),
                ("signer", models.CharField(max_length=42)),
                ("deployed_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_deleted", models.IntegerField(default=0, null=True)),
            ],
            options={
                "db_table": "bot",
            },
        ),
    ]
