# Generated by Django 5.0.6 on 2024-08-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0010_bot"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bot",
            old_name="signer",
            new_name="owner",
        ),
        migrations.AddField(
            model_name="bot",
            name="is_failed",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="bot",
            name="number_used",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
