# Generated by Django 5.0.6 on 2024-08-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0011_rename_signer_bot_owner_bot_is_failed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="is_holding",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
