# Generated by Django 5.0.6 on 2024-08-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0012_bot_is_holding"),
    ]

    operations = [
        migrations.AddField(
            model_name="blacklist",
            name="frozen_at",
            field=models.DateTimeField(null=True),
        ),
    ]
