# Generated by Django 5.0.6 on 2024-08-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0014_position_investment_position_returns"),
    ]

    operations = [
        migrations.CreateModel(
            name="Executor",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("address", models.CharField(max_length=42, unique=True)),
                ("initial_balance", models.FloatField(default=0, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_deleted", models.IntegerField(default=0, null=True)),
            ],
            options={
                "db_table": "executor",
            },
        ),
        migrations.CreateModel(
            name="PnL",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField()),
                ("number_positions", models.IntegerField(default=0, null=True)),
                ("hourly_pnl", models.FloatField(default=0, null=True)),
                ("avg_daily_pnl", models.FloatField(default=0, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_deleted", models.IntegerField(default=0, null=True)),
            ],
            options={
                "db_table": "pnl",
            },
        ),
    ]
