# Generated by Django 5.0.6 on 2024-08-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0017_pnl_number_failed"),
    ]

    operations = [
        migrations.AddField(
            model_name="pair",
            name="deployed_block",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
