# Generated by Django 5.0.6 on 2024-08-31 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0018_pair_deployed_block"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="is_paper",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
